print("Hello World")
print("Hello","World")
print("Hi","How","Are","You")
print('hello world')
print(1*1)
print("""multi line statement.going to third line """)
print("multi line statement.going to third line")
print('''multi line statement.going going to third line''')
#PRINT("HELLO WORLD")
#print "hello world!"
print(100)
print(1+5)
print(1/1)
print(10,20,30)
print("my age is",8)
print('my age is',8)
print("python" *3)
print("hello","world",sep=" ")
print('hello','world',sep='-')
print('hello','world',sep='_')
print('hello','world',sep=',')


